1. si no lo hiciste, descargá los headers de tu kernel (instrucciones en el LEV tp3)

2. descarga esta mierda y extrae

3. metele make al encriptador y despues: sudo insmod encriptador.ko

4. metele make al desencriptador y despues: sudo insmod desencriptador.ko

te deberian aparecer ambos modulos en: lsmod | head

5. make user (no hay makefile... todavia) y corre el user en root

6.disfruta de esta meirda
